### PR TITLE
Sync js-api tests from wpt.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by gahaas — APPROVED** [review]
Thanks!

**Comment by rossberg** [comment]
Is there a reason not to land this?

**Comment by Ms2ger** [comment]
I'm guessing I missed the review, and now #1449 landed everything except the v128 change, which should probably go into wpt instead.

**Comment by rossberg** [comment]
Okay, thanks. I deleted the PR branch from the repo.

**Pull request closed without merging**
