### PR TITLE
[test] Add tests ensuring table type is grown in `table.grow`

### PR DESCRIPTION
**Pull request by dzfrias**
No previous tests check that `table.grow` grows the table instance's type. This was found when implementing LibWasm for the Ladybird browser.

### CODE REVIEW

**Review by rossberg — COMMENTED** [review]
The test looks good to me, but this should go to table_grow.wast (imports are only used as a means for observing the table's runtime type).

**Comment by dzfrias** [comment]
A similar test for `memory.grow` is in `imports.wast`. Should I move both?

**Comment by rossberg** [comment]
Ah, good point. Yeah, that is ancient, and worth moving as well.

**Comment by dzfrias** [comment]
Ok, I just moved them to their respective files. Thank you!

**Review by rossberg — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
