### PR TITLE
Implement tables & multiple memories

### PR DESCRIPTION
**Pull request by rossberg-chromium**
As of WebAssembly/design#682. Still misses import/export abilities.

This changes & extends the S-expression syntax for tables and memories in the following way:
```
<elem_type>: anyfunc
<table>:     (table <nat> <nat>? <elem_type>)
<memory>:    (memory <nat> <nat>?)
<elem>:      (elem <expr> <var>*)
<data>:      (data <expr> <string>*)
```
In particular, memory segments are no longer part of the `memory` definition, in anticipation of the ability to import memory. Same for tables. This also mirrors the Wasm section structure more closely.

However, it is pretty tedious to count table elements in the common case, so the following shorthand is available:
```
(table <elem_type> (elem <var>*))    ;; = (table <size> <size> <elem_type>) (elem (i32.const 0) <var>*)
```
which pretty much behaves like the previous table syntax.
For symmetry, I introduced the analogous shorthand for memories, which turns out to be useful in tests as well:
```
(memory (data <string>*))   ;; = (memory <size> <size>) 
(data (i32.const 0) <string>*)
```
where `<size>` is the strings' total length in (rounded up) page units.

In the future, we can extend this syntax to name tables and memories, e.g.:
```
<table>:   (table <name>? <nat> <nat>? <elem_type>)
<memory>:  (memory <name>? <nat> <nat>?)
<elem>:    (elem <var>? <expr> <var>*)
<data>:    (data <var>? <expr> <string>*)
```

### CODE REVIEW

**Comment by kripken** [comment]
What is the plan with the `stack` branch - will this be merged there as well as to `binary-0xc`? Or will `stack` eventually be merged to `binary-0xc` without doing that first?

**Comment by rossberg-chromium** [comment]
Excellent question. I meant to merge everything into binary-0xc eventually. But I'm still cleaning up the stack branch somewhat, and I suppose reviewing it may also take some time. So I didn't want everything else to block on that.

Guess that means that I gonna have a merge-conflict fest at some point...

**Comment by kripken** [comment]
In the tests it looks like `data` can either be nested in `memory` or not. What is the difference?

**Comment by rossberg-chromium** [comment]
See the first comment above. ;)

**Comment by kripken** [comment]
Ok, sorry, I thought it was just about tables.

**Comment by lukewagner** [comment]
The s-expr changes lgtm

**Comment by lukewagner** [comment]
I think we also need new syntax for importing a tables/memories; we currently use:
  `( import <name>? <string> <string> ( table <nat> <nat>? <elem_type> ) )`
  `( import <name>? <string> <string> ( memory <nat> <nat>? ) )`

**Comment by rossberg-chromium** [comment]
Any concerns about landing this?

**Comment by lukewagner** [comment]
righto, generally lgtm

**Pull request merged**
