### PR TITLE
Add tests for alignment overflow

### LINKED ISSUE #1749: Test extreme alignments
Currently tests only test alignment slightly greater than usual. It would be useful to test extreme alignments like 9223372036854775808, we think. These can often fail in UBSAN.

### PR DESCRIPTION
**Pull request by SoniEx2**
let's see what CI says about these...

closes #1749

### CODE REVIEW

**Comment by SoniEx2** [comment]
heh. looks like the test is working as intended. ^^

but also. uh, how do you fix that one?

```
../test/core/_output/align.wast.bin.wast.wast:1269.47-1269.54: syntax error: alignment must be a power of two
```

```wast
(assert_invalid
  (module
    (type $0 (func))
    (memory $0 1)
    (func $0 (type 0) (i32.const 0) (i32.load align=0) (drop))
  )
  "alignment must not be larger than natural"
)
```

**Comment by rossberg** [comment]
To assert malformed text format, you'll need to use `module quote`, which defers parsing.

**Comment by SoniEx2** [comment]
take a look at the filename again, it's a roundtrip(?) one. we found a bug in the roundtrip(?) function.

**Comment by rossberg** [comment]
Ah, actually, the bug is in the decoder not considering 2^32 malformed (which then overflows into 0 when converting to text).

Can you try changing the `le_u` in interpreter/binary/decode.ml:223 to `lt_e`?

**Review by rossberg — APPROVED** [review]
Thanks. (But please never force-push to a branch under review, that breaks GH PR mechanics.)

**Comment by SoniEx2** [comment]
oh, really? sorry, we're so used to force-pushing for other projects we contribute to, but we'll keep it in mind.

**Comment by rossberg** [comment]
Well, it's a common mistake, but you shouldn't do that for any GH project. As just one example of what breaks, [here](https://github.com/WebAssembly/spec/pull/1751/files/b2e95b5d1231ad49d0b381a1af39483e5697c79c..9a09f09f6c6191706ae4a39b6c0aee905f3029ae) is what happens to commit links; reviewers lose relative diffs and diff links, comments get orphaned or vanish, etc.

**Pull request merged**
