### PR TITLE
Improve build and fix typos

### PR DESCRIPTION
**Pull request by littledan**
* Fix links to the web-api specification 
* Remove Markdown use in an HTML page
* [spec] Implement spec deployment for JS specs

@rossberg

### CODE REVIEW

**Comment by littledan** [comment]
Ping @rossberg ; the current version of this patch includes bbd90c3  which uses Travis-CI to rebuild the bikeshed-based specs. I left out the main WebAssembly specification from automation since I haven't figured out how to build it locally yet, but it should be straightforward to add if someone can write a script for the installation of the appropriate tools.

To make the Travis-CI part work to deploy on the main WebAssembly repo, I'd need admin access to set up the deployment key on GitHub and Travis-CI and put it into this patch (or, otherwise, someone else needs to do that).

**Comment by littledan** [comment]
@rossberg Moved. However, this patch needs some work from someone with admin rights on this repository to set up the GitHub deploy key. Does someone want to give me those rights, or otherwise, I could walk someone who has those rights through the process?

**Comment by rossberg** [comment]
IIRC the current policy is to limit admin rights to one rep per browser vendor.

@lukewagner, can you help out Dan?

**Comment by lukewagner** [comment]
Well, that was more of a way to get everything set up than an enduring hard rule; plus browser vendors is all we had at the beginning and now we, thankfully, have many more entities involved.  I can't imagine why you both shouldn't be Admins to the spec repo, being the two primary spec authors, so added you both.

**Comment by littledan** [comment]
Thanks, @lukewagner ! I added a Travis CI deploy key. Should this be good to land now?

**Pull request merged**
