### PR TITLE
Check all segment bounds beforehand

### PR DESCRIPTION
**Pull request by rossberg-chromium**
...and add tests that memories/tables remain unchanged in case of error. Addresses WebAssembly/design#897

### CODE REVIEW

**Comment by jfbastien** [comment]
I would rather check bounds as we apply segments, instead of up front. IMO it's not a useful property to purposefully apply segments and *rely* on halfway failure, but it's faster to check each bounds while applying them versus doing two passes. I'd therefore do a single pass, and fail halfway. This optimizes for the useful case (everything succeeds) and leaves the useless case in a well-specified state.

**Comment by rossberg-chromium** [comment]
@jfbastien, I agree that's simpler, but if you prefer that semantics then I suggest you create a PR to change JS.md.

**Comment by jfbastien** [comment]
Done: https://github.com/WebAssembly/design/pull/902

**Comment by gahaas** [comment]
lgtm

**Comment by rossberg-chromium** [comment]
@jfbastien, are you fine with landing this for the time being? Until we have consensus for changing the design the spec should better match the current design.

**Comment by jfbastien** [comment]
@rossberg-chromium with that rationale we could as well merge https://github.com/WebAssembly/design/pull/902, no? I'm OK revisiting later, so feel free to merge as long as we discuss this.

**Comment by rossberg-chromium** [comment]
@jfbastien, thanks. There doesn't seem to be consensus on the broader change from #902, but the overriding goal is to get design and spec into sync. We can always adjust the spec when #902 evolves.

**Pull request merged**
