### PR TITLE
Create Github Actions workflow for CI

### PR DESCRIPTION
**Pull request by takikawa**
This addresses issue #1342 for publishing the spec on commit, and also adds CI using Github Actions for the interpreter and spec documents.

It appears that Travis CI has switched to a paid model beyond a certain compute limit (see https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), which is I think why the spec auto-publish has not been running recently.

You can see the rendered spec resulting from this PR on this page: https://takikawa.github.io/spec/index.html (the gh-pages branch itself is here: https://github.com/takikawa/spec/tree/gh-pages and the detailed log from the build process can be seen here: https://github.com/takikawa/spec/actions/runs/1019012134)

To see the CI on pull requests in action, you can look at these testing PRs here:
  * https://github.com/takikawa/spec/pull/1
  * https://github.com/takikawa/spec/pull/2
  * https://github.com/takikawa/spec/pull/3

### CODE REVIEW

**Review by rossberg — APPROVED** [review]
Awesome, thanks!

I have to admit that I'm out of my depths reviewing this PR, but if it works I'm happy to rubberstamp it. I'd say feel free to land if nobody else chimes in...

**Comment by Ms2ger** [comment]
Can you update https://github.com/WebAssembly/proposals/blob/master/howto.md ?

**Comment by takikawa** [comment]
> Can you update https://github.com/WebAssembly/proposals/blob/master/howto.md ?

Now done in this PR: https://github.com/WebAssembly/proposals/pull/113

**Comment by rossberg** [comment]
From WebAssembly/proposals#113 it looks like the deploy_key is no longer needed with this PR, so perhaps remove the file?

**Comment by takikawa** [comment]
> From [WebAssembly/proposals#113](https://github.com/WebAssembly/proposals/pull/113) it looks like the deploy_key is no longer needed with this PR, so perhaps remove the file?

I added a commit to remove this and a few other files related to using Travis-CI (let me know if that's removing too much).

Additionally, I added an extra commit to replace the build status icon in the README with a Github Actions one (note: it doesn't display properly on my fork, but it should work once it's merged).

**Review by Ms2ger — APPROVED** [review]
Let's try it out.

**Pull request merged**
