### PR TITLE
Add testing for reserved bytes

### LINKED ISSUE #700: A few binary tests for reserved bytes
The following module are contains grow_memory, current_memory, call_indirect with reserved byte isn't equal to 0 (all in base64 encoding)

```
AGFzbQEAAAABBAFgAAADAgEABQMBAAAKCQEHAEEAQAEaCwAKBG5hbWUCAwEAAA
```

```
AGFzbQEAAAABBAFgAAADAgEABQMBAAAKBwEFAD8BGgsACgRuYW1lAgMBAAA=
```

```
AGFzbQEAAAABBAFgAAADAgEABAQBcAAACgkBBwBBABEAAQsACgRuYW1lAgMBAAA=
```

I'm wondering are you interested in adding these tests in binary.wast? If so, I could make a PR.

### PR DESCRIPTION
**Pull request by pepyakin**
Resolves #700 

Just testing the grounds. Am I going in the right direction @rossberg  ?

### CODE REVIEW

**Comment by pepyakin** [comment]
If I remember correctly, I have already joined the CG. Should I give my email or something?

**Comment by pepyakin** [comment]
Ah, yeh, here is my profile https://www.w3.org/users/102125

**Comment by rossberg** [comment]
I'm afraid I don't have access rights to your profile. Can you please make sure that you are listed on the members list? (Sorry for the nuisance.)

**Comment by pepyakin** [comment]
No problem, I can confirm that I'm in the participants list.

**Comment by rossberg** [comment]
> No problem, I can confirm that I'm in the participants list.

Well, that's a start, but to land your patch we need to be able to confirm it on our end. And the only way I can do that is by checking whether your name shows up in the official [participants list](https://www.w3.org/community/webassembly/participants). Unfortunately, it's not there, so what I was asking is for you to investigate why and get the list updated. Sorry for the pain!

**Comment by pepyakin** [comment]
> Unfortunately, it's not there

Yeah, that's because in github it's not my real name. My real name is a `Sergey Shulepov`. Sorry for the confusion.

**Pull request merged**
