### PR TITLE
wasm-compatible float32 and float64 arithmetic

### PR DESCRIPTION
**Pull request by sunfishcode**
This PR is not yet ready for merging!

This is some exploratory code implementing wasm-compatible float64 arithmetic in OCaml. This is my first ML code and I'm still learning, so please don't be gentle. Also, it doesn't compile yet because I haven't figured out how to use int64 yet. And, it doesn't have tests yet. And nothing is using it yet. And it may be buggy. I'm interested in any and all feedback about the approach, how best to structure the code, coding style, or anything.

I expect to eventually refactor this code to support float32 as well.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Updated to address review feedback. Lots of changes including using modules and abstract types, and using the new operators in spec code. This still lacks tests.

**Comment by sunfishcode** [comment]
The functor refactoring is looking like it's going to take me a while, and this is starting to slow progress elsewhere; would you be ok if we deferred the functor refactoring and just checked in this branch as it stands here? The redundancy isn't actually that bad.

Also, while there are no tests here yet, I am planning to write extensive tests for all the code here, and it would actually be more convenient to submit these tests incrementally instead of bundling them all up into a single monolithic patch.

**Comment by rossberg-chromium** [comment]
On 16 September 2015 at 18:14, Dan Gohman <notifications@github.com> wrote:

> The functor refactoring is looking like it's going to take me a while, and
> this is starting to slow progress elsewhere; would you be ok if we deferred
> the functor refactoring and just checked in this branch as it stands here?
> The redundancy isn't actually that bad.
>
> Also, while there are no tests here yet, I am planning to write extensive
> tests for all the code here, and it would actually be more convenient to
> submit these tests incrementally instead of bundling them all up into a
> single monolithic patch.
>

Sure. I'm also happy to do the refactoring after you land this version.

**Comment by sunfishcode** [comment]
Ok, great. I'll merge this now and we can continue to iterate on this code in tree.

**Pull request merged**
