### PR TITLE
[interpreter] Proper fix for JS conversion

### PR DESCRIPTION
**Pull request by rossberg**
This reverts #1829 and implements a simpler & correcter fix.

### CODE REVIEW

**Comment by backes** [comment]
This makes most tests pass, thanks!

There are still other issues, but that's probably unrelated. E.g. in the generated `type-rec.js`:
```
223 // type-rec.wast:69
224 let $$3 = module("\x00 [...] \x0b");
225 let M = $$3;
226
227 // type-rec.wast:69
228 let $3 = instance(M);
229 let M = $3;
```
(double definition of `M`)

**Review by backes — APPROVED** [review]

**Comment by backes** [comment]
At some point someone should just run all tests in `wasm-3.0` against a JS engine and fix all those issues. I can't fix anything in the OCaml code, so I am not the right person for this. Maybe @sbc100 is already doing that as part of #1828.

**Comment by rossberg** [comment]
Ah, just fixed that as well, can you try now? (Sorry I can test this on my end, as I am travelling.)

**Comment by backes** [comment]
No problem, I can try and report back.

We now have a similar problem with
```
243 // type-rec.wast:80
244 assert_unlinkable(instance($$5));
```

This should be `assert_unlinkable(module($$5))`.

**Comment by rossberg** [comment]
Ah, sorry, next try. :)  (It should actually just be `assert_unlinkable($$5)`, I think.)

**Comment by rossberg** [comment]
Landed. Thanks for your patience. :)

**Comment by backes** [comment]
Thanks for fixing this!

I created PRs to merge the new wasm-3.0 branch into memory64 and jspi (I hope this is how this works):
https://github.com/WebAssembly/memory64/pull/89
https://github.com/WebAssembly/js-promise-integration/pull/50

**Pull request merged**
