### PR TITLE
[interpreter] Fix float literals

### PR DESCRIPTION
**Pull request by gahaas**
I cannot compile the spec interpreter with ToT. This PR fixes the problem for me. I tried to compile with ocaml 4.02.3, 4.06.0, and 4.08.0, by just running `make`.

### CODE REVIEW

**Comment by KronicDeth** [comment]
It is unfortunate that the original does not work.  It is much clearer you are using a max value.  Could we put the values into named constants to make it clearer that they are max for a given bit width?

**Comment by rossberg** [comment]
Yeah, hex float constants were introduced with Ocaml 4.03, which is from 3+ years ago. Do you still need support for 4.02? Current is 4.08.

**Comment by gahaas** [comment]
I think I forgot to do `make clean`, that's why I was not able to compile it, even with 4.08. The instructions in interpreter/README.md still mention 4.02. Could you adjust it to the version that is actually needed?

**Comment by rossberg** [comment]
Ah, wanted to say that after reconsideration, cutting backwards compatibility does not seem worth it (yet), and we should land this after all. Too late though, so I created #1044, PTAL.

**Pull request closed without merging**
