### PR TITLE
Make grow_memory and return pages, and replace memory_size with current_memory

### PR DESCRIPTION
**Pull request by rossberg-chromium**
To match WebAssembly/design#629 and WebAssembly/design#648.

### CODE REVIEW

**Comment by lukewagner** [comment]
lgtm, yes, we should update/add `memory_size` too

**Comment by rossberg-chromium** [comment]
Okay, I added `memory_size` to this PR, PTAL.

**Comment by lukewagner** [comment]
lgtm.  One question I just remembered, and the reason I didn't simply throw in the `memory_size` update with [design/#629](https://github.com/WebAssembly/design/pull/629), is that "size" doesn't sound quite right if the returned unit is pages.  That could be a separate issue, though.

**Comment by rossberg-chromium** [comment]
Agreed. `current_memory` perhaps?

**Comment by lukewagner** [comment]
Yes, that has a nice symmetry with `grow_memory`.

**Comment by rossberg-chromium** [comment]
Okay, updated with a rename memory_size -> current_memory. Corresponding design PR is WebAssembly/design#648. PTAL

**Comment by lukewagner** [comment]
Great, lgtm (assuming no objections to design PR).

**Comment by rossberg-chromium** [comment]
Landing with LGTM and no objections

**Pull request merged**
