### PR TITLE
[spec] Fix module context for constants

### LINKED ISSUE #1711: Question about validation of {element, data} segments
The [spec](https://webassembly.github.io/spec/core/valid/modules.html#valid-module) tells that we have to validate element and data segments under context C' defined as follows.

context_C

However, that means the active element and data segments are always invalid, because C'.tables and C'.mems are always empty. Is this a specification error? Or am I missing something?

validate_elemet_segment

validate_data

### PR DESCRIPTION
**Pull request by rossberg**
Fix #1711.

### CODE REVIEW

**Comment by rossberg** [comment]
@conrad-watt, ping.

**Comment by rossberg** [comment]
@conrad-watt, ping again.

**Review by conrad-watt — APPROVED** [review]
LGTM - this will change again with the GC proposal, where global initialisers can refer to previously-declared globals, right?

**Comment by rossberg** [comment]
Yes, that's right.

**Pull request merged**
