### PR TITLE
Allow creation of default i64 global values

### PR DESCRIPTION
**Pull request by binji**
See issue #827.

### CODE REVIEW

**Comment by binji** [comment]
Good point, though this is a relatively minor change, we should discuss it in the CG.

**Comment by littledan** [comment]
I'm fine with it not going through a stage process, but process-wise, you might want to lay out a lightweight set of conditions for a tiny normative change like this to be added to the standard. For example, TC39 requires conformance tests for normative changes, even if they don't go through the stage process.

**Comment by binji** [comment]
That's a good idea, though currently it seems that we've just taken a poll for changes like this. Perhaps there needs to be more for direct changes to the spec, however.

**Comment by lars-t-hansen** [comment]
IMO this needs a CG poll.  While I agree this ought to be uncontroversial and I contemplated including this behavior when implementing globals in SpiderMonkey, it's a visible non-bug-fix spec change and should not quietly slip in.

**Comment by rossberg** [comment]
I agree this should have a CG poll.

**Comment by binji** [comment]
Added to tomorrow's CG, though the agenda is pretty full so it may be pushed to the next meeting.

**Comment by binji** [comment]
We discussed this in the June 26th CG meeting and decided to include this change in the v1 spec.

**Comment by littledan** [comment]
Is this ready to merge then?

**Pull request merged**
