### PR TITLE
Fix some editorial issues with the JS API specification.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by binji** [comment]
> With respect to the W3C process, is it too late to merge this PR?

I discussed w/ Brad, and we're currently past the 90-day mark anyway, so we're always at least 90-days out at this point. Which is to say, it's not too late. :)

**Comment by littledan** [comment]
>  he also said that that in general, non-functional changes like this do not affect the clock.

OK, merging this patch then.

**Comment by littledan** [comment]
@Ms2ger Could you rebase? It seems that there is a conflict.

**Comment by Ms2ger** [comment]
Rebased.

**Pull request merged**
