### PR TITLE
Simplify builtins module

### PR DESCRIPTION
**Pull request by rossberg-chromium**
A temporary measure, since the LLVM producer can only generate empty names currently.

### CODE REVIEW

**Comment by sunfishcode** [comment]
It seems like it'd be better to put something in wasmate.py to add module names, since it is effectively a linking function. Also, that way this issue stays relatively localized, rather than spread around to all s-expr consumers.

**Comment by rossberg-chromium** [comment]
Yeah, I don't have a specific opinion on this. This change was requested as a stop-gap measure by several people. Note that producers who use the module name will also continue to work just fine, so not necessarily a need for anybody else to adjust.

**Comment by lukewagner** [comment]
+1 on solving this in wasmate.py, since it can simply and unconditionally splat in "stdio", right?

**Comment by kg** [comment]
Yeah, based on my experience with ilwasm I think wasmate should just put in stdio.

**Comment by rossberg-chromium** [comment]
Okay, sounds good. I removed the actual ignoring part from this patch. Since it also contained some clean-up, I'dd like to land the rest anyway. Retitled accordingly. PTAL.

**Comment by sunfishcode** [comment]
The cleanup part lgtm.

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/WebAssembly/experimental/pull/48 to wasmate implementing the wasmate suggestion here.

**Pull request merged**
