### PR TITLE
Allow optional argument to br_if

### PR DESCRIPTION
**Pull request by rossberg-chromium**
Matching up with v8-prototype and https://github.com/WebAssembly/design/pull/464 .

Also, add simple test for br_if.

### CODE REVIEW

**Comment by titzer** [comment]
lgtm

**Comment by AndrewScheidecker** [comment]
The way this is implemented, the argument must not be evaluated unless the condition is true. AFAICT that means it must be implemented with two hardware branches, contrary to the motivation for `br_if`. It seems strange, but maybe the argument should always be evaluated?

**Comment by titzer** [comment]
In v8-native, the argument is indeed always evaluated.

**Comment by rossberg-chromium** [comment]
@AndrewScheidecker: good point, refined accordingly in #188.

**Pull request merged**
