### PR TITLE
Automatically recompile the spec interpreter before generating the tests

### PR DESCRIPTION
**Pull request by bnjbvr**
#453 is a case of bad UX: a developer would expect that `build.py` just generates the tests. What's hidden in there is that the test generator uses the wasm spec interpreter, so it needs to be up to date and compiled in the first place.

This PR makes that we recompile the spec interpreter before generating the tests, unless explicitly told not to (with `--dont-recompile`).

@rossberg-chromium, can you have a look, please?

### CODE REVIEW

**Comment by bnjbvr** [comment]
It seems all the checks have passed and @rossberg-chromium approved the patch, is this ready to be merged?

**Comment by rossberg-chromium** [comment]
@bnjbvr, you should become a committer. ;)

**Comment by jfbastien** [comment]
He's already in the https://github.com/orgs/WebAssembly/teams/workshop group, doesn't that allow him to merge?

**Comment by lukewagner** [comment]
Only as of today :)

**Pull request merged**
