### PR TITLE
Remove obsolete nan-propagation.wast.

### PR DESCRIPTION
**Pull request by gahaas**
NaN propagation has been removed from the design repo, which made the nan-propagation tests obsolete. this PR removes the nan-propagation tests.

### CODE REVIEW

**Comment by rossberg-chromium** [comment]
Does this require changes to the implementation as well? If so, we should perhaps do them together.

In any case, can you please retarget the PR on the binary-0xc branch?

**Comment by titzer** [comment]
The change landed on master, IIUC. If so, then it's probably best to go
ahead and remove these tests on master, too.

**Comment by rossberg-chromium** [comment]
I see. In that case sgtm, but we should merge to binary-0xc after.

@sunfishcode, you probably know best: IIUC the change is purely a relaxation, but is there anything that can/should be simplified in the impl of arithmetics now to reflect it?

**Comment by sunfishcode** [comment]
This change lgtm.

`determine_binary_nan` and `determine_unary_nan` could indeed be simplified, though as you observe, it's not necessary.

I've updated https://github.com/WebAssembly/spec/issues/286 with notes about the remaining missing NaN test coverage.

**Comment by rossberg-chromium** [comment]
@gahaas, feel free to land this. Bonus points if you also make the simplifications that @sunfishcode mentioned (see `float.ml`). :)

**Pull request merged**
