### PR TITLE
[spec] Fix side condition about fresh ids

### LINKED ISSUE #1313: Identifiers can seemingly be replaced with fresh identifiers
In [6.6.5.1](https://webassembly.github.io/spec/core/bikeshed/#abbreviations%E2%91%A0%E2%93%AA), the condition on the rewrite rule is (if `id`′ = `id`<sup>?</sup> !​= ϵ ∨ `id`′ fresh), which suggests that as long as `id`′ is a fresh identifier, the rule can be applied. So even if the declaration already has an identifier, that identifier can be replaced with a fresh one.

That seems wrong and unintentional, as it would break any references to the original identifier. The right side of the condition should probably be changed to something like (`id`′ fresh ∧ `id`<sup>?</sup> = ϵ).

Same thing applies to the many similar rewrite rules for other types of declarations.

### PR DESCRIPTION
**Pull request by rossberg**
Fixes #1313.

### CODE REVIEW

**Comment by rossberg** [comment]
@dtig, friendly ping.

**Comment by rossberg** [comment]
@SpecLad, could you verify the fixes and perhaps approve this PR?

**Review by SpecLad — APPROVED** [review]
Sure. Looks good to me.

**Comment by rossberg** [comment]
Thanks!

**Pull request merged**
