### PR TITLE
Endianness test

### PR DESCRIPTION
**Pull request by pjuftring**
This tests, if all load and store operations use little-endian.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Please use spaces rather than tabs, for consistency with the other tests. Otherwise this lgtm.

**Comment by jfbastien** [comment]
@pjuftring, could you confirm that you're a [W3C CG](https://www.w3.org/community/webassembly/participants) participant (it seems so) and that you're not representing a company in particular? Thanks!

**Comment by pjuftring** [comment]
@jfbastien I'm a W3C CG participant and not representing a company.

**Comment by sunfishcode** [comment]
Great, thanks!

**Pull request merged**
