### PR TITLE
[test] Add more tests for operand missing -Part2

### PR DESCRIPTION
**Pull request by Honry**
This is the second part to fix following task in typecheck.wast:
;; TODO(stack): more of the above

### CODE REVIEW

**Comment by Honry** [comment]
@rossberg, PTAL.

**Comment by Honry** [comment]
@rossberg, thanks for the comment! I agree on you that so much combinations look like meaningless.  
So how about narrow down the scope in 3~4 combinations or smaller?

**Comment by rossberg** [comment]
I'm of course fine with landing more tests, and I appreciate all the effort you are putting into this. But I am worried that the benefit of tests like these may be too marginal to justify spending more of your precious time with them.

On the other hand, there are features for which we have too few tests at the moment, e.g. tables, segments, edge cases of the binary format, etc. Some of them don't even have their own file. Can I perhaps get you interested in shifting focus to those? :)

**Comment by Honry** [comment]
@rossberg, I'm also appreciate your patient and careful reviews. Actually I have already prepared the rest operand missing tests in local, so there won't be too much time to spend on it. :)

After complete all TODOs in typecheck.wast, I will shift my focus to those features with few tests you mentioned.

**Pull request merged**
