### PR TITLE
[test] Import v128 global

### PR DESCRIPTION
**Pull request by rossberg**
Adds a simple test for ex/importing a global of type v128.

@ajklein, @jakobkummerow, this makes V8's InstanceBuilder crash, presumably because v128 isn't handled [here](https://github.com/v8/v8/blob/main/src/wasm/module-instantiate.cc#L1446) (tested with node 18.14.0, the CI failure is caused by that as well).

### CODE REVIEW

**Comment by ajklein** [comment]
Thanks, filed https://crbug.com/v8/13732 to track the V8 crash.

**Review by jakobkummerow — APPROVED** [review]

**Comment by rossberg** [comment]
Thanks. @jakobkummerow, do you happen to know the rough turn-around time for a V8 fix to make it downstream into node? I'm hesitant to land this PR right now, since I'd have to disable running JS tests in CI to make it green.

**Comment by rossberg** [comment]
> As a short-term workaround, you could make the global mutable (with a `TODO` comment to add a test for an immutable global as well, once the V8 fix has propagated far enough).

Done.

**Comment by tomstuart** [comment]
It’s surprising that this appears in a `test/core/*.wast` test script instead of `test/core/simd/*.wast`. All other occurrences of `v128` appear in `test/core/simd/*.wast`.

**Comment by rossberg** [comment]
Good point, will fix.

**Pull request merged**
