### PR TITLE
Update version to 1

### PR DESCRIPTION
**Pull request by binji**

### CODE REVIEW

**Comment by binji** [comment]
Any reason to hold off on this, or should we land when travis is green?

**Comment by bnjbvr** [comment]
Can you also update `kWasmV0` in test/harness/wasm-constants.js?

**Comment by eholk** [comment]
@bnjbvr I opened #434 to update wasm-constants.js, although it'd probably make more sense to include that change here instead.

**Comment by binji** [comment]
Just updated here, sorry for the delay. :)

**Pull request merged**
