### PR TITLE
Mark trunk as Editor's Draft.

### PR DESCRIPTION
**Pull request by flagxor**

### CODE REVIEW

**Comment by jfbastien** [comment]
Is your goal to have a FPWD branch, and keep master as ED?

**Comment by flagxor** [comment]
Only the version hosted by the W3C is considered the actual fPWD, and I got emailed with by someone confused about that.
The version in github.com/WebAssembly/spec is considered the "Editor's Draft" and there's different labeling that should mark that clearly (this will switch on the right kind of red editor's draft labeling + disclaimer).
Ideally I'd like to land this in bikeshed first:
https://github.com/tabatkins/bikeshed/pull/1194
(as without it this change will have an empty status section).

I've tagged master-fpwd and gh-pages-fpwd marking the version pulled in by W3C.
We could also do a branch if you think that's clearer than a tag?

For future drafts, we either can hand them a cooked copy like we did this time (for the first draft that was the only option). Alternatively, bikeshed can apparently be setup to talk to automation on their end, though I'm a little worried that won't work with out Frankenstein build (as I believe the plumbing runs bikeshed on w3c bots). I haven't had a chance to sort that out with Tab.

**Comment by rossberg** [comment]
It would probably give us more flexibility if we had a branch for the FPWD version. That way we could cherry-pick changes from master and wouldn't be forced to block master's progress with new features.

**Comment by flagxor** [comment]
I'll branch fpwd, but then actually add a wd branch, as strictly only the first draft is fpwd.

**Comment by flagxor** [comment]
I've created branches fpwd and working_draft off the starting point.
Here's a CL to tag the working draft branch: https://github.com/WebAssembly/spec/pull/717
We can then merge master changes to it periodically.

Review over there, but I suppose maybe that should be tagged as editor's draft too, instead of WD. Depends on if we add automation to publish it. If it's manual it would only ever go to W3C I suppose.

**Comment by flagxor** [comment]
Actually though, come to think of it, aside from cooking a version tagged as WD, why would master be blocked on landing features?
I.e. I had thought we wouldn't merge one of the proposal repos until it's ready to be part of the next upcoming editor's draft? (i.e. that's why I was marking master with ED).

**Comment by jfbastien** [comment]
> It would probably give us more flexibility if we had a branch for the FPWD version. That way we could cherry-pick changes from master and wouldn't be forced to block master's progress with new features.

Exactly what I thought.

> Actually though, come to think of it, aside from cooking a version tagged as WD, why would master be blocked on landing features?
> I.e. I had thought we wouldn't merge one of the proposal repos until it's ready to be part of the next upcoming editor's draft? (i.e. that's why I was marking master with ED).

Because then we can have a living standard as the ED, in master, and be blissfully ignorant of Official W3C Editions. Only spec maintainers need to know of and be careful with branches, everyone else merges to master. Only if you know you want to be in a particular W3C release do you ever ask for a cherry-pick to a branch.

**Comment by flagxor** [comment]
Ok sounds good.
So basically couple folks can periodically carefully merge things to working_draft, possibly waiting to do so until we feel we want to issue a new draft (or are required to do so by the 6 month clock).

Then sounds like CLs are fine as is. Just need to wait to land on bikeshed change.
The status stuff living inside bikeshed is a little odd, but oh well.

**Comment by jfbastien** [comment]
I think we'll want a working draft branch per 6 month, so that we can see old drafts and so it's easier to just branch tip-of-tree each 6 month without fiddling with old crufty branches.

Of course this requires more work than just holding off merges, so I'd have @rossberg and @littledan sign off on the plan. For sanity it would be great to have @domenic chime in.

**Comment by littledan** [comment]
> I think we'll want a working draft branch per 6 month, so that we can see old drafts and so it's easier to just branch tip-of-tree each 6 month without fiddling with old crufty branches.

To check if I understand, are you suggesting this?
- Master is always an Editor's Draft
- Every 6 months, we fork a Working Draft version that is intended to go to a Recommendation eventually

If so, I'm wildly supportive of this plan.

> Only if you know you want to be in a particular W3C release do you ever ask for a cherry-pick to a branch.

FWIW ECMAScript basically never cherry-picks features to annual branches. If you miss the train, you just wait a year and catch the next one. And for WebAssembly, this should be even less of a concern since you only have to wait six months. Never merging in features and always just forking significantly reduces the work of spec maintainers while still keeping feature development on a fully official standards track.

**Comment by jfbastien** [comment]
@littledan Yes to what you wrote.

> FWIW ECMAScript basically never cherry-picks features to annual branches. If you miss the train, you just wait a year and catch the next one. And for WebAssembly, this should be even less of a concern since you only have to wait six months. Never merging in features and always just forking significantly reduces the work of spec maintainers while still keeping feature development on a fully official standards track.

Agreed on that model, except for the current draft there are editorial changes to cherry-pick. That's some amount of work for editors because they go in master, and then you need to cherry-pick them.

**Comment by littledan** [comment]
@jfbastien Yes, there's definitely still editor work (right @bterlson ?), and editorial changes do sometimes need to be backported.

**Comment by flagxor** [comment]
Bikeshed side change landed.
So it sounds like having master marked "Editor's Draft" is what we want to do.
Any objection to landing this PR?

**Comment by flagxor** [comment]
Merging in the interest of getting the incorrectly marked thing switched (and as all above seem to assume master will be marked ED).

Sounds like we'll want to clarify when we start rolling new versions.
I've added an agenda item for the next WG meeting to discuss.

**Pull request merged**
