### PR TITLE
[spec] Document index and makefiles

### PR DESCRIPTION
**Pull request by rossberg**
* Add a new index page for the different spec documents.

* Put the actual documents into respective sub directories.

* Add toplevel Makefile and README, and Makefiles for each spec document (yet to be filled out).

* Tweak & move deploy file to toplevel.

* Leave the actually make targets for building the Bikeshed-based API specs as TODOs.

### CODE REVIEW

**Comment by rossberg** [comment]
Finally managed to work around the ridiculous semantics with gh-pages and Jekyll by adding a .nojekyll file. Suffice to say that none of this is properly documented. Unfortunately, this solution requires the index file to be in plain HTML. If anybody wants to waste their lifetime figuring out a better solution, then please be my guest, but for now I intend to leave it as is.

**Comment by rossberg** [comment]
Yes, the multiple reference warnings are normal. This is a problem with Sphinx' handling of anchors, and I couldn't find a way to work around it. However, the PDF should still build successfully. But on my system it actually builds with pdflatex, not latexmk. Which version of Sphinx are you using?

In any case, you should be able to just use `make publish-js-api` (or `make publish` in the respective directory) and not worry about the core spec build.

**Comment by rossberg** [comment]
Btw, the publish targets should also work on a fork, to publish a version for review.

**Comment by littledan** [comment]
> Yes, the multiple reference warnings are normal. This is a problem with Sphinx' handling of anchors, and I couldn't find a way to work around it. However, the PDF should still build successfully. But on my system it actually builds with pdflatex, not latexmk. Which version of Sphinx are you using?

Looks like v1.6.3 (that's what pip seemed to give me...). FWIW I do have pdflatex installed. Which version of sphinx should I be using?

**Comment by rossberg** [comment]
Hm, found out that the switch from pdflatex to latexmk came with Sphinx 1.6 (https://github.com/sphinx-doc/sphinx/blob/master/CHANGES), which I haven't updated to yet. I'll look into it, but can't promise much before next year.

**Comment by rossberg** [comment]
@littledan, I have upgraded to the latest Sphinx (1.6.5) and all works fine. The multiply-defined labels warnings are there as usual, but I still see no errors. So probably latexmk wasn't the issue.

Do you still have that problem? If so, can you paste the actual Latex error messages that you get?

**Comment by littledan** [comment]
@rossberg I upgrade from 1.6.3 to 1.6.5 and everything seems good now. Maybe this was a bug that they fixed.

**Comment by littledan** [comment]
Sorry, false alarm: `make html` is fine, but `make pdf` still gives me a mess of errors. Here's the first several (I pressed enter to continue through these). IMO getting `make html` into CI is an important goal in itself--JS manages to do alright with pdf dumps only once a year--so I'll work on that first.

```
littledan@littledan-ThinkPad-T460p:~/spec/document/core$ make pdf
sphinx-build -b latex -d _build/doctrees -D latex_paper_size=a4  . _build/latex
Running Sphinx v1.6.5
WARNING: while setting up extension ['?', 'mathdef']: node class 'math' is already registered, its visitors will be overridden
WARNING: while setting up extension ['?', 'mathdef']: node class 'displaymath' is already registered, its visitors will be overridden
WARNING: while setting up extension mathdef: role 'math' is already registered, it will be overridden
WARNING: while setting up extension mathdef: directive 'math' is already registered, it will be overridden
WARNING: unknown config value 'latex_paper_size' in override, ignoring
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing WebAssembly.tex...index intro/index intro/introduction intro/overview syntax/index syntax/conventions syntax/values syntax/types syntax/instructions syntax/modules valid/index valid/conventions valid/types valid/instructions valid/modules exec/index exec/conventions exec/runtime exec/numerics exec/instructions exec/modules binary/index binary/conventions binary/values binary/types binary/instructions binary/modules text/index text/conventions text/lexical text/values text/types text/instructions text/modules appendix/index appendix/embedding appendix/implementation appendix/algorithm appendix/custom appendix/properties appendix/index-types appendix/index-instructions appendix/index-rules 
resolving references...
writing... done
copying TeX support files...
done
build succeeded, 5 warnings.
Running LaTeX files through pdflatex...
make -C _build/latex all-pdf
make[1]: Entering directory '/home/littledan/spec/document/core/_build/latex'
latexmk -pdf -dvi- -ps-  'WebAssembly.tex'
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'WebAssembly.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex   -recorder  "WebAssembly.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./WebAssembly.tex
LaTeX2e <2016/02/01>
Babel <3.9q> and hyphenation patterns for 3 language(s) loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2017/03/26 v1.6 Document class (Sphinx manual)
(/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)))
(/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)<<t1.cmap>>)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def)))
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/times.sty)

! LaTeX Error: File `fncychap.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 

! LaTeX Error: Unknown option `Sonny' for package `fncychap'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.32 \usepackage
                [dontkeepoldnames]{sphinx}
? 
(./sphinx.sty (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty))))
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))

! LaTeX Error: File `titlesec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 

! LaTeX Error: File `tabulary.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Undefined control sequence.
<recently read> \newcolumntype 
                               
l.74 \newcolumntype
                   {\X}[2]{p{\dimexpr
? 
! Undefined control sequence.
l.74 \newcolumntype{\X
                      }[2]{p{\dimexpr
? 

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.74 \newcolumntype{\X}[
                        2]{p{\dimexpr
? 
! You can't use `\dimexpr' in horizontal mode.
l.74 \newcolumntype{\X}[2]{p{\dimexpr
                                     
? 
! You can't use `macro parameter character #' in horizontal mode.
l.75       (\linewidth-\arrayrulewidth)*#
                                         1/#2-\tw@\tabcolsep-\arrayrulewidth...

? 
! You can't use `macro parameter character #' in horizontal mode.
l.75       (\linewidth-\arrayrulewidth)*#1/#
                                            2-\tw@\tabcolsep-\arrayrulewidth...

? 
! Undefined control sequence.
l.76 \newcolumntype
                   {\Y}[1]{p{\dimexpr
? 
! Undefined control sequence.
l.76 \newcolumntype{\Y
                      }[1]{p{\dimexpr
? 
! You can't use `\dimexpr' in horizontal mode.
l.76 \newcolumntype{\Y}[1]{p{\dimexpr
                                     
? 
! You can't use `macro parameter character #' in horizontal mode.
l.77       #
            1\dimexpr\linewidth-\arrayrulewidth\relax-\tw@\tabcolsep-\arrayr...

? 
! You can't use `\dimexpr' in horizontal mode.
l.77       #1\dimexpr
                     \linewidth-\arrayrulewidth\relax-\tw@\tabcolsep-\arrayr...

? 
! Undefined control sequence.
l.79 \newcolumntype
                   {T}{J}%
? 
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)

! LaTeX Error: File `varwidth.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
(./sphinxmulticell.sty
! Undefined control sequence.
<argument> \tymin 
                  
l.25 \setlength{\tymin}{3\fontcharwd\font`0 }
                                             % minimal width of "squeezed" c...

? 
! You can't use `\fontcharwd' in horizontal mode.
<argument> 3\fontcharwd 
                        \font `0 
l.25 \setlength{\tymin}{3\fontcharwd\font`0 }
                                             % minimal width of "squeezed" c...

? 
! Missing control sequence inserted.
<inserted text> 
                \inaccessible 
l.25 \setlength{\tymin}{3\fontcharwd\font`0 }
                                             % minimal width of "squeezed" c...

? 
kpathsea:make_tex: Invalid fontname ``0', contains '`'
! Font \inaccessible=`0 not loadable: Metric (TFM) file not found.
<to be read again> 
                   \relax 
l.25 \setlength{\tymin}{3\fontcharwd\font`0 }
                                             % minimal width of "squeezed" c...

? 
! Undefined control sequence.
<argument> \tymax 
                  
l.26 \setlength{\tymax}{10000pt}
                                % allow enough room for paragraphs to "compete"

? 
! Undefined control sequence.
l.39 \expandafter\sphinx@tempa\TY@tab
                                     \sphinx@tempa
? 
)
Runaway argument?
\sphinx@tempa \def \sphinxstartmulticolumn {\ifx \equation $\expandafter \ETC.
! File ended while scanning use of \sphinx@tempa.
<inserted text> 
                \par 
l.150 \RequirePackage
                     {makeidx}
? 
(/usr/share/texlive/texmf-dist/tex/latex/base/makeidx.sty)

! LaTeX Error: File `framed.sty' not found.
```

And here's the end of the output:

```
l.14825 \hline
              
? 
No file WebAssembly.ind.
[150] (./WebAssembly.aux
)

LaTeX Warning: There were multiply-defined labels.

 ){/usr/share/texlive/texmf-dist/fonts/enc/dvips/base/8r.enc} </home/littledan/
.texmf-var/fonts/pk/ljfour/jknappen/ec/ecrm1000.600pk></usr/share/texlive/texmf
-dist/fonts/type1/public/amsfonts/cm/cmex10.pfb></usr/share/texlive/texmf-dist/
fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/share/texlive/texmf-dist/fonts/
type1/public/amsfonts/cm/cmmi5.pfb></usr/share/texlive/texmf-dist/fonts/type1/p
ublic/amsfonts/cm/cmmi7.pfb
></usr/share/texlive/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts
/cm/cmr5.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr7
.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmss10.pfb><
/usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmss8.pfb></usr/sh
are/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb></usr/share/te
xlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy5.pfb></usr/share/texlive/t
exmf-dist/fonts/type1/public/amsfonts/cm/cmsy7.pfb></usr/share/texlive/texmf-di
st/fonts/type1/public/amsfonts/cm/cmti10.pfb></usr/share/texlive/texmf-dist/fon
ts/type1/public/amsfonts/cm/cmti7.pfb></usr/share/texlive/texmf-dist/fonts/type
1/public/amsfonts/cm/cmtt10.pfb></usr/share/texlive/texmf-dist/fonts/type1/publ
ic/amsfonts/symbols/msam10.pfb></usr/share/texlive/texmf-dist/fonts/type1/publi
c/amsfonts/symbols/msbm10.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/co
urier/ucrb8a.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/courier/ucrr8a.
pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/uhvb8a.pfb></usr/sh
are/texlive/texmf-dist/fonts/type1/urw/helvetic/uhvbo8a.pfb></usr/share/texlive
/texmf-dist/fonts/type1/urw/helvetic/uhvr8a.pfb></usr/share/texlive/texmf-dist/
fonts/type1/urw/times/utmb8a.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw
/times/utmr8a.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/times/utmri8a.
pfb>

Output written on WebAssembly.pdf (159 pages, 1065762 bytes).
Transcript written on WebAssembly.log.

Latexmk: Missing input file: 'fncychap.sty' from line
  '! LaTeX Error: File `fncychap.sty' not found.'

Latexmk: Missing input file: 'titlesec.sty' from line
  '! LaTeX Error: File `titlesec.sty' not found.'
Latexmk: Missing input file: 'tabulary.sty' from line
  '! LaTeX Error: File `tabulary.sty' not found.'
Latexmk: Missing input file: 'varwidth.sty' from line
  '! LaTeX Error: File `varwidth.sty' not found.'
Latexmk: Missing input file: 'framed.sty' from line
  '! LaTeX Error: File `framed.sty' not found.'
Latexmk: Missing input file: 'wrapfig.sty' from line
  '! LaTeX Error: File `wrapfig.sty' not found.'
Latexmk: Missing input file: 'upquote.sty' from line
  '! LaTeX Error: File `upquote.sty' not found.'
Latexmk: Missing input file: 'capt-of.sty' from line
  '! LaTeX Error: File `capt-of.sty' not found.'
Latexmk: Missing input file: 'needspace.sty' from line
  '! LaTeX Error: File `needspace.sty' not found.'
Latexmk: Index file 'WebAssembly.idx' was written


Latexmk: Missing input file: 'WebAssembly.ind' from line
  'No file WebAssembly.ind.'
Latexmk: Log file says output to 'WebAssembly.pdf'
Latexmk: List of undefined refs and citations:
  Label `appendix/custom:binary-indirectnamemap' multiply defined
  Label `appendix/properties:frame-context' multiply defined
  Label `appendix/properties:module-context' multiply defined
  Label `appendix/properties:valid-val' multiply defined
  Label `binary/modules:binary-code' multiply defined
  Label `binary/modules:binary-data' multiply defined
  Label `binary/modules:binary-elem' multiply defined
  Label `binary/modules:binary-export' multiply defined
  Label `binary/modules:binary-exportdesc' multiply defined
  Label `binary/modules:binary-func' multiply defined
  Label `binary/modules:binary-funcidx' multiply defined
  Label `binary/modules:binary-global' multiply defined
  Label `binary/modules:binary-globalidx' multiply defined
  Label `binary/modules:binary-import' multiply defined
  Label `binary/modules:binary-importdesc' multiply defined
  Label `binary/modules:binary-labelidx' multiply defined
  Label `binary/modules:binary-local' multiply defined
  Label `binary/modules:binary-localidx' multiply defined
  Label `binary/modules:binary-magic' multiply defined
  Label `binary/modules:binary-mem' multiply defined
  Label `binary/modules:binary-memidx' multiply defined
  Label `binary/modules:binary-start' multiply defined
  Label `binary/modules:binary-table' multiply defined
  Label `binary/modules:binary-tableidx' multiply defined
  Label `binary/modules:binary-typedef' multiply defined
  Label `binary/modules:binary-typeidx' multiply defined
  Label `binary/modules:binary-version' multiply defined
  Label `binary/types:binary-blocktype' multiply defined
  Label `binary/types:binary-elemtype' multiply defined
  Label `binary/types:binary-mut' multiply defined
  Label `binary/values:binary-sint' multiply defined
  Label `binary/values:binary-uint' multiply defined
  Label `binary/values:binary-utf8' multiply defined
  Label `exec/instructions:exec-label' multiply defined
  Label `exec/instructions:exec-load' multiply defined
  Label `exec/instructions:exec-memarg' multiply defined
  Label `exec/instructions:exec-store' multiply defined
  Label `exec/modules:exec-import' multiply defined
  Label `exec/modules:exec-module' multiply defined
  Label `exec/numerics:aux-fbias' multiply defined
  Label `exec/numerics:aux-fsign' multiply defined
  Label `exec/numerics:aux-littleendian' multiply defined
  Label `exec/numerics:exec-op-partial' multiply defined
  Label `exec/runtime:frame' multiply defined
  Label `exec/runtime:label' multiply defined
  Label `exec/runtime:page-size' multiply defined
  Label `exec/runtime:syntax-frame' multiply defined
  Label `exec/runtime:syntax-funcaddr' multiply defined
  Label `exec/runtime:syntax-funcelem' multiply defined
  Label `exec/runtime:syntax-globaladdr' multiply defined
  Label `exec/runtime:syntax-hostfunc' multiply defined
  Label `exec/runtime:syntax-init-data' multiply defined
  Label `exec/runtime:syntax-init-elem' multiply defined
  Label `exec/runtime:syntax-invoke' multiply defined
  Label `exec/runtime:syntax-label' multiply defined
  Label `exec/runtime:syntax-memaddr' multiply defined
  Label `exec/runtime:syntax-store' multiply defined
  Label `exec/runtime:syntax-tableaddr' multiply defined
  Label `exec/runtime:syntax-thread' multiply defined
  Label `exec/runtime:syntax-trap' multiply defined
  Label `syntax/conventions:notation-concat' multiply defined
  Label `syntax/conventions:notation-record' multiply defined
  Label `syntax/conventions:notation-replace' multiply defined
  Label `syntax/conventions:notation-slice' multiply defined
  Label `syntax/instructions:syntax-binop' multiply defined
  Label `syntax/instructions:syntax-block' multiply defined
  Label `syntax/instructions:syntax-br' multiply defined
  Label `syntax/instructions:syntax-br-if' multiply defined
  Label `syntax/instructions:syntax-br-table' multiply defined
  Label `syntax/instructions:syntax-call' multiply defined
  Label `syntax/instructions:syntax-call-indirect' multiply defined
  Label `syntax/instructions:syntax-const' multiply defined
  Label `syntax/instructions:syntax-cvtop' multiply defined
  Label `syntax/instructions:syntax-fbinop' multiply defined
  Label `syntax/instructions:syntax-frelop' multiply defined
  Label `syntax/instructions:syntax-ftestop' multiply defined
  Label `syntax/instructions:syntax-funop' multiply defined
  Label `syntax/instructions:syntax-ibinop' multiply defined
  Label `syntax/instructions:syntax-if' multiply defined
  Label `syntax/instructions:syntax-instr-seq' multiply defined
  Label `syntax/instructions:syntax-irelop' multiply defined
  Label `syntax/instructions:syntax-itestop' multiply defined
  Label `syntax/instructions:syntax-iunop' multiply defined
  Label `syntax/instructions:syntax-loadn' multiply defined
  Label `syntax/instructions:syntax-loop' multiply defined
  Label `syntax/instructions:syntax-memarg' multiply defined
  Label `syntax/instructions:syntax-nop' multiply defined
  Label `syntax/instructions:syntax-relop' multiply defined
  Label `syntax/instructions:syntax-return' multiply defined
  Label `syntax/instructions:syntax-storen' multiply defined
  Label `syntax/instructions:syntax-sx' multiply defined
  Label `syntax/instructions:syntax-testop' multiply defined
  Label `syntax/instructions:syntax-unop' multiply defined
  Label `syntax/instructions:syntax-unreachable' multiply defined
  Label `syntax/modules:syntax-exportdesc' multiply defined
  Label `syntax/modules:syntax-funcidx' multiply defined
  Label `syntax/modules:syntax-globalidx' multiply defined
  Label `syntax/modules:syntax-importdesc' multiply defined
  Label `syntax/modules:syntax-labelidx' multiply defined
  Label `syntax/modules:syntax-local' multiply defined
  Label `syntax/modules:syntax-localidx' multiply defined
  Label `syntax/modules:syntax-memidx' multiply defined
  Label `syntax/modules:syntax-tableidx' multiply defined
  Label `syntax/modules:syntax-typeidx' multiply defined
  Label `syntax/types:syntax-elemtype' multiply defined
  Label `syntax/types:syntax-mut' multiply defined
  Label `syntax/values:syntax-codepoint' multiply defined
  Label `syntax/values:syntax-nan' multiply defined
  Label `syntax/values:syntax-payload' multiply defined
  Label `syntax/values:syntax-sint' multiply defined
  Label `syntax/values:syntax-uint' multiply defined
  Label `text/conventions:text-context-wf' multiply defined
  Label `text/instructions:text-blockinstr' multiply defined
  Label `text/instructions:text-plaininstr' multiply defined
  Label `text/lexical:source' multiply defined
  Label `text/lexical:text-format' multiply defined
  Label `text/lexical:text-keyword' multiply defined
  Label `text/lexical:text-reserved' multiply defined
  Label `text/lexical:text-source' multiply defined
  Label `text/modules:text-datastring' multiply defined
  Label `text/modules:text-exportdesc' multiply defined
  Label `text/modules:text-funcidx' multiply defined
  Label `text/modules:text-globalidx' multiply defined
  Label `text/modules:text-importdesc' multiply defined
  Label `text/modules:text-labelidx' multiply defined
  Label `text/modules:text-local' multiply defined
  Label `text/modules:text-localidx' multiply defined
  Label `text/modules:text-memidx' multiply defined
  Label `text/modules:text-modulefield' multiply defined
  Label `text/modules:text-tableidx' multiply defined
  Label `text/modules:text-typeidx' multiply defined
  Label `text/types:text-elemtype' multiply defined
  Label `text/types:text-param' multiply defined
  Label `text/types:text-result' multiply defined
  Label `text/values:text-byte' multiply defined
  Label `text/values:text-digit' multiply defined
  Label `text/values:text-frac' multiply defined
  Label `text/values:text-hexdigit' multiply defined
  Label `text/values:text-hexfloat' multiply defined
  Label `text/values:text-hexfrac' multiply defined
  Label `text/values:text-hexnum' multiply defined
  Label `text/values:text-idchar' multiply defined
  Label `text/values:text-num' multiply defined
  Label `text/values:text-sign' multiply defined
  Label `text/values:text-sint' multiply defined
  Label `text/values:text-uint' multiply defined
  Label `valid/instructions:valid-label' multiply defined
  Label `valid/instructions:valid-memarg' multiply defined
  Label `valid/modules:valid-exportdesc' multiply defined
  Label `valid/modules:valid-importdesc' multiply defined
  Label `valid/modules:valid-local' multiply defined
Latexmk: Summary of warnings:
  Latex found 153 multiply defined reference(s)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Makefile:33: recipe for target 'WebAssembly.pdf' failed
make[1]: *** [WebAssembly.pdf] Error 12
make[1]: Leaving directory '/home/littledan/spec/document/core/_build/latex'
Makefile:192: recipe for target 'latexpdf' failed
make: *** [latexpdf] Error 2
```

**Comment by rossberg** [comment]
@littledan, that very much looks like your Latex installation is broken somehow: it doesn't find some required packages, the rest is just cascading errors.

**Pull request merged**
