### PR TITLE
[interpreter] Fix subtype condition for result patterns

### PR DESCRIPTION
**Pull request by rossberg**
This should fix WebAssembly/memory64#95.

### CODE REVIEW

**Comment by rossberg** [comment]
@backes, that is odd, I don't see that error on the wasm-3.0 branch. I amended the PR, that should address the assertion failure you're seeing. Let me know if that works.

**Comment by rossberg** [comment]
Okay, there were a couple of issues with the generation of JS wrapper modules for ref.extern (and also `either` patterns). Those didn't pop up on this branch, because no wrapper modules were needed in any of the cases where ref.extern was used.

I also added a sanity check that all generated modules are valid, and activated CI for the wasm-3.0 branch, so that these problems should get caught earlier in the future.

**Review by backes — APPROVED** [review]
Nice, this seems to fix all issues!

**Comment by backes** [comment]
I am merging this, and then creating a PR on `memory64` to merge the updated `wasm-3.0` branch.

**Pull request merged**
