### PR TITLE
[spec] Tweak wording

### PR DESCRIPTION
**Pull request by rossberg**
Address #960.

### CODE REVIEW

**Comment by rossberg** [comment]
I assumed the other concern would be disambiguated by saying "as a power" (as opposed to "as powers"). The other I'm not sure.

Or perhaps we can simply remove the paren altogether?

**Comment by binji** [comment]
> Or perhaps we can simply remove the paren altogether?

Maybe so, but I'd read that as specifying the alignment as being 1, 2, 4, 8, etc. in that case.

**Comment by rossberg** [comment]
"expressed as the exponent of a power of 2"?

**Comment by binji** [comment]
Yes, that sounds right to me. It's a bit of a mouthful, but I can't think of a more succinct way to say it.

**Pull request merged**
