### PR TITLE
Fix the path to the wasm executable to match what the Makefile builds.

### LINKED ISSUE #59: multiple build processes, processes disagree
When using src/Makefile, one gets an executable at src/wasm. However, runtests.py expects an executable at src/main.native. It'd be useful for these to agree; which one is preferable?

### PR DESCRIPTION
**Pull request by sunfishcode**
This fixes #59. I have no idea if it works on Windows. If this fix is inappropriate, please tell me what I can do to fix this instead. Thanks!

### CODE REVIEW

**Comment by pjuftring** [comment]
The travis-testscript still creates "main.native" and therefore fails.
Everything's fine on Windows, at least on Cygwin.

**Comment by sunfishcode** [comment]
@pjuftring Fixed, thanks!

**Comment by rossberg-chromium** [comment]
I suspect this breaks the `--build` option of the script, unless you also
adapt the `rebuildInterpreter` function. Now that the Makefile is using
ocamlbuild, the function should probably just invoke that instead of
duplicating the parameters.

**Comment by sunfishcode** [comment]
I updated --build to just invoke the Makefile. It Works For Me (tm).

**Comment by sunfishcode** [comment]
Merging, because it fixes #59 and no one has objected so far.

**Pull request merged**
