### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by naltun**
Change `incomplet` => `incomplete` and `inkorrekt` => `incorrect` to adhere to grammatical English spelling.

### CODE REVIEW

**Comment by rossberg-chromium** [comment]
That's an intentional pun, see also #263, #266, and a few older PRs. ;)

**Comment by naltun** [comment]
Haha, then you can reference mine for the future. I found it QUITE odd that those mistakes would have persisted for so long, yet I dared venture to update the README.. Good stuff. Cheers! :+1:

**Comment by kripken** [comment]
Actually, if this is a recurring issue, perhaps we should merge this? Or add `(sp)` or a link, as hints?

**Comment by kpmy** [comment]
Guys, plz, don't forget to run make land, winmake is now inconsistent.

**Comment by rossberg-chromium** [comment]
@kpmy, a sorry, that was probably my fault. Should be fixed now.

Also, I put the "incomplet and inkorrect" in quotes, to make it more apparent that it's intentional.

**Comment by naltun** [comment]
If you guys ever need help with maintaining the project (I particularly like documentation), then I'd be happy to help.

**Comment by dschuff** [comment]
I don't know that we're likely to have someone officially designated to do things like maintain documentation, but I'm sure we'd be happy to take patches from anyone that wants to send them, so if you see something you want to improve, you are welcome :)

**Comment by naltun** [comment]
:+1: Brilliant!

**Pull request closed without merging**
